-- MySQL Script generated by MySQL Workbench
-- Wed Dec  4 12:57:48 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `dni` INT NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Provincia` (
  `ID` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Localidad` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `codigoPostal` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `idProvincia` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Localidad_Provincia1_idx` (`idProvincia` ASC) VISIBLE,
  CONSTRAINT `fk_Localidad_Provincia1`
    FOREIGN KEY (`idProvincia`)
    REFERENCES `mydb`.`Provincia` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Domicilio` (
  `ID` INT NOT NULL,
  `calle` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `piso` VARCHAR(45) NULL,
  `departamento` VARCHAR(45) NULL,
  `idLocalidad` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Domicilio_Localidad1_idx` (`idLocalidad` ASC) VISIBLE,
  CONSTRAINT `fk_Domicilio_Localidad1`
    FOREIGN KEY (`idLocalidad`)
    REFERENCES `mydb`.`Localidad` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servicio` (
  `ID` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conexion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conexion` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `fechaAlta` DATE NOT NULL,
  `numero` DATE NOT NULL,
  `idCliente` INT NOT NULL,
  `idDomicilio` INT NOT NULL,
  `idServicio` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Conexion_Cliente_idx` (`idCliente` ASC) VISIBLE,
  INDEX `fk_Conexion_Domicilio1_idx` (`idDomicilio` ASC) VISIBLE,
  INDEX `fk_Conexion_Servicio1_idx` (`idServicio` ASC) VISIBLE,
  CONSTRAINT `fk_Conexion_Cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Conexion_Domicilio1`
    FOREIGN KEY (`idDomicilio`)
    REFERENCES `mydb`.`Domicilio` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Conexion_Servicio1`
    FOREIGN KEY (`idServicio`)
    REFERENCES `mydb`.`Servicio` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Visita` (
  `ID` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `observacion` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `idConexion` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Visita_Conexion1_idx` (`idConexion` ASC) VISIBLE,
  CONSTRAINT `fk_Visita_Conexion1`
    FOREIGN KEY (`idConexion`)
    REFERENCES `mydb`.`Conexion` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Operador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Operador` (
  `ID` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `legajo` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Soporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Soporte` (
  `ID` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `motivo` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `idConexion` INT NOT NULL,
  `idOperador` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Soporte_Conexion1_idx` (`idConexion` ASC) VISIBLE,
  INDEX `fk_Soporte_Operador1_idx` (`idOperador` ASC) VISIBLE,
  CONSTRAINT `fk_Soporte_Conexion1`
    FOREIGN KEY (`idConexion`)
    REFERENCES `mydb`.`Conexion` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Soporte_Operador1`
    FOREIGN KEY (`idOperador`)
    REFERENCES `mydb`.`Operador` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tecnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tecnico` (
  `ID` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `legajo` INT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VisitaTecnico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VisitaTecnico` (
  `ID` INT NOT NULL,
  `IdVisita` INT NOT NULL,
  `idTecnico` INT NOT NULL,
  INDEX `fk_Visita_has_Tecnico_Tecnico1_idx` (`idTecnico` ASC) VISIBLE,
  INDEX `fk_Visita_has_Tecnico_Visita1_idx` (`IdVisita` ASC) VISIBLE,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_Visita_has_Tecnico_Visita1`
    FOREIGN KEY (`IdVisita`)
    REFERENCES `mydb`.`Visita` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Visita_has_Tecnico_Tecnico1`
    FOREIGN KEY (`idTecnico`)
    REFERENCES `mydb`.`Tecnico` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
